---
- hosts: default
  become: true
  tasks:
    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

    - include: partition.yml
    - include: remote.yml

    - name: clone kvm-vmi repo
      shell: cd /data && git clone https://github.com/KVM-VMI/kvm-vmi
      become: false

    - name: clone submodules
      shell: cd /data/kvm-vmi/kvm && git submodule update --init
      become: false

    - include: kvm.yml
    - include: nitro.yml
    - include: qemu.yml
    - include: test_vm.yml
