---
- hosts: default
  become: true
  tasks:
    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

    - include: partition.yml
    - include: remote.yml

    - name: clone kvm-vmi repo
      command: git clone https://github.com/KVM-VMI/kvm-vmi
      args:
        chdir: /data
      become: false

    - name: clone submodules
      command: git submodule update --init
      args:
        chdir: "{{ root_dir }}/kvm"
      become: false

    - include: kvm.yml
    - include: nitro.yml
    - include: qemu.yml
    - include: test_vm.yml
