---
- hosts: default
  become: true
  tasks:
    - name: add backports
      lineinfile:
        dest: /etc/apt/sources.list
        line: 'deb http://ftp.debian.org/debian jessie-backports main contrib non-free'
        insertafter: EOF

    - name: add backports sources
      lineinfile:
        dest: /etc/apt/sources.list
        line: 'deb-src http://ftp.debian.org/debian jessie-backports main contrib non-free'
        insertafter: EOF

    - name: update cache
      apt:
        update_cache: yes

    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

    - include: remote.yml
    - include: kvm.yml
    - include: nitro.yml
    - include: qemu.yml
    - include: test_vm.yml
