---
- hosts: all
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: install useful tools
      package:
        name: "{{ item }}"
      with_items:
        - git
        - htop
        - vim

  roles:
    - partition
    - kvm
