---
- name: update cache
  apt:
    update_cache: yes

- name: install build dependencies
  package:
    name: "{{ item }}"
  with_items:
    - bc
    - fakeroot
    - dpkg-dev
    - flex
    - bison
    - libelf-dev
    - libssl-dev

- name: configure kernel using distro's config
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# disable trusted keys debian/certs/debian-uefi-certs.pem
# as they are only available in the kernel sources, and we don't
# care about SecureBoot
- name: disable SYSTEM_TRUSTED_KEYS
  command: ./scripts/config --disable SYSTEM_TRUSTED_KEYS
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: disable MODULE_SIG_KEY
  command: ./scripts/config --disable MODULE_SIG_KEY
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# configure KVM
- name: enable KVM
  command: ./scripts/config --enable KVM
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTEL
  command: ./scripts/config --enable KVM_INTEL
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_AMD
  command: ./scripts/config --enable KVM_AMD
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# KVM_INTROSPECTION depends on REMOTE_MAPPING,
# which depends on KSM being disabled
- name: disable KSM
  command: ./scripts/config --disable KSM
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable REMOTE_MAPPING
  command: ./scripts/config --enable REMOTE_MAPPING
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTROSPECTION
  command: ./scripts/config --enable KVM_INTROSPECTION
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: append -kvmi to kernel version string
  lineinfile:
    dest: "{{ root_dir }}/kvm/Makefile"
    regexp: '^EXTRAVERSION ='
    line: 'EXTRAVERSION = -kvmi'
  become: false

- name: set default config to new options
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: build kernel and make debian package
  command: "make -j{{ ansible_processor_vcpus }} deb-pkg"
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false
  environment:
    # strip modules to reduces initramfs size by x10
    # otherwise /boot will be full
    INSTALL_MOD_STRIP: "1"

- name: find generated debian packages
  find:
    paths: "{{ root_dir }}"
    patterns: "*.deb"
  register: deb_list
  become: false

- name: install kernel debian packages
  apt:
    deb: "{{ item.path }}"
    state: present
  with_items:
    "{{ deb_list.files }}"
  loop_control:
    label: "{{ item.path }}"
  become: true

- name: set kvmi kernel as default
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT="1>0"'

- name: update GRUB configuration
  command: update-grub

- name: setup libkvmi
  include: libkvmi.yml
