---
- name: update cache
  apt:
    update_cache: yes

- name: install build dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - libelf-dev
    - libssl-dev
    - fakeroot
    - dpkg-dev
    - bc

- name: configure kernel using distro's config
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM
  command: ./scripts/config --enable KVM
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTEL
  command: ./scripts/config --enable KVM_INTEL
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_AMD
  command: ./scripts/config --enable KVM_AMD
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVMI
  command: ./scripts/config --enable KVMI_MEM_GUEST
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: append -kvmi to kernel version string
  lineinfile: 
    dest: "{{ root_dir }}/kvm/Makefile"
    regexp: '^EXTRAVERSION ='
    line: 'EXTRAVERSION = -kvmi'
  become: false

- name: set default config to new options
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: compile kernel
  command: make -j4 bzImage
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: compile modules
  command: make -j4 modules
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: install modules
  command: make modules_install
  args:
    chdir: "{{ root_dir }}/kvm"

- name: install kernel
  command: make install
  args:
    chdir: "{{ root_dir }}/kvm"

- name: set kvmi kernel as default
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT="1>0"'

- name: update GRUB configuration
  command: update-grub
